-- 코드를 입력하세요
SELECT HISTORY_ID, CAR_ID, date_format(START_DATE,'%Y-%m-%d'),  date_format(END_DATE, '%Y-%m-%d'),
CASE
    WHEN datediff(END_DATE, START_DATE) >= 29 THEN '장기 대여'
    ELSE '단기 대여'
END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) = 9
ORDER BY HISTORY_ID DESC;
