SELECT 
    YEAR(S.SALES_DATE) YEAR, MONTH(S.SALES_DATE) MONTH , 
    COUNT(DISTINCT S.USER_ID) as PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / 
          (SELECT COUNT(*) FROM USER_INFO
           WHERE YEAR(JOINED) = 2021), 1) PUCHASED_RATIO
FROM USER_INFO U
JOIN ONLINE_SALE S
ON U.USER_ID = S.USER_ID
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
ORDER BY YEAR, MONTH;

