-- 코드를 입력하세요
SELECT CAR_ID, ROUND(AVG(datediff(end_date, start_date)+1),1) as AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING ROUND(AVG(datediff(end_date, start_date)),1) >= 6
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;
